// APP
export const START_NEW_GAME = 'START_NEW_GAME'
export const RESET_CURRENT_GAME = 'RESET_CURRENT_GAME'
export const OPEN_SETTINGS_MENU = 'OPEN_SETTINGS_MENU'
export const CLOSE_SETTINGS_MENU = 'CLOSE_SETTINGS_MENU'
export const SHOW_POISON_COUNTERS = 'SHOW_POISON_COUNTERS'
export const HIDE_POISON_COUNTERS = 'HIDE_POISON_COUNTERS'
export const SHOW_COMMANDER_COUNTERS = 'SHOW_COMMANDER_COUNTERS'
export const HIDE_COMMANDER_COUNTERS = 'HIDE_COMMANDER_COUNTERS'

// PLAYERS
export const ADD_PLAYER = 'ADD_PLAYER'
export const REMOVE_PLAYER = 'REMOVE_PLAYER'
export const CHOOSE_COLOR = 'CHOOSE_COLOR'
export const INCREASE_LIFE = 'INCREASE_LIFE'
export const DECREASE_LIFE = 'DECREASE_LIFE'
export const ADD_POISON_COUNTER = 'ADD_POISON_COUNTER'
export const REMOVE_POISON_COUNTER = 'REMOVE_POISON_COUNTER'
export const ADD_COMMANDER_DAMAGE = 'ADD_COMMANDER_DAMAGE'
export const REMOVE_COMMANDER_DAMAGE = 'REMOVE_COMMANDER_DAMAGE'

// AUTH
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL'
export const SIGN_IN_PROVIDER_REQUEST = 'SIGN_IN_PROVIDER_REQUEST'
export const SIGN_IN_PROVIDER_FAIL = 'SIGN_IN_PROVIDER_FAIL'
export const SIGN_IN_PROVIDER_SUCCESS = 'SIGN_IN_PROVIDER_SUCCESS'
export const SAVE_USER = 'SAVE_USER'

// GAME
export const CREATE_GAME = 'CREATE_GAME'
export const DESTROY_GAME = 'DESTROY_GAME'

// ERRORS
export const SHOW_ERROR = 'SHOW_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'
export const HIDE_ALL_ERRORS = 'HIDE_ALL_ERRORS'
