// APP
export const OPEN_SETTINGS_MENU = 'OPEN_SETTINGS_MENU'
export const CLOSE_SETTINGS_MENU = 'CLOSE_SETTINGS_MENU'
// PLAYERS
export const ADD_PLAYER = 'ADD_PLAYER'
export const REMOVE_PLAYER = 'REMOVE_PLAYER'
export const CHOOSE_COLOR = 'CHOOSE_COLOR'
export const ADD_LIFE = 'ADD_LIFE'
export const REMOVE_LIFE = 'REMOVE_LIFE'
export const ADD_POISON_COUNTER = 'ADD_POISON_COUNTER'
export const REMOVE_POISON_COUNTER = 'REMOVE_POISON_COUNTER'
export const ADD_COMMANDER_DAMAGE = 'ADD_COMMANDER_DAMAGE'
export const REMOVE_COMMANDER_DAMAGE = 'REMOVE_COMMANDER_DAMAGE'
